### ISSUE TITLE
请问如何恢复默认字体

### ISSUE THREAD

**Issue by Mqpzi** [leijunCN/Windows-Fonts#2]
用大佬给出的方法替换后，想恢复系统默认字体该怎么做呢？试了控制面板>>字体>>字体设置，点击“还原默认字体设置”，没有变化

**Comment by leijunCN** [comment]
这个安装包版本其实用的是安装后替换了注册表，可以去注册表里修改一下改成默认值。例如：msyh.ttc
可以参考这个文章 https://blog.csdn.net/Xm3333691/article/details/120482343 ，如果还不行的话，根据名称去卸载一下安装好的字体。

**Comment by Mqpzi** [comment]
> 这个安装包版本其实用的是安装后替换了注册表，可以去注册表里修改一下改成默认值。例如：msyh.ttc 可以参考这个文章 https://blog.csdn.net/Xm3333691/article/details/120482343 ，如果还不行的话，根据名称去卸载一下安装好的字体。

感谢，不过我换的是新版微软雅黑，字体文件名跟旧版完全一样，导致新的直接把旧的覆盖了，但注册表里的值没变……因为系统正在使用这些字体，也卸载不了。这种情况只能重装系统了吗

**Comment by leijunCN** [comment]
虽然但是，如果你需要重新安装系统的话，推荐你可以用这个网站试试 https://uupdump.net/ ，根据当前的系统版本生成ISO，可以保留数据的方式进行原地重装当前版本。
因为我改了以后就没有恢复过原来的字体，所以能提供的帮助也不多... ，也可以去找找有没有官方的字体版本装一下，再改注册表




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月12日(星期一) 中午11:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [leijunCN/Windows-Fonts] 请问如何恢复默认字体 (Issue #2)














  
这个安装包版本其实用的是安装后替换了注册表，可以去注册表里修改一下改成默认值。例如：msyh.ttc 可以参考这个文章 https://blog.csdn.net/Xm3333691/article/details/120482343 ，如果还不行的话，根据名称去卸载一下安装好的字体。
  
感谢，不过我换的是新版微软雅黑，字体文件名跟旧版完全一样，导致新的直接把旧的覆盖了，但注册表里的值没变……因为系统正在使用这些字体，也卸载不了。这种情况只能重装系统了吗

**Comment by Mqpzi** [comment]
> 虽然但是，如果你需要重新安装系统的话，推荐你可以用这个网站试试 https://uupdump.net/ ，根据当前的系统版本生成ISO，可以保留数据的方式进行原地重装当前版本。 因为我改了以后就没有恢复过原来的字体，所以能提供的帮助也不多... ，也可以去找找有没有官方的字体版本装一下，再改注册表
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年8月12日(星期一) 中午11:11 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [leijunCN/Windows-Fonts] 请问如何恢复默认字体 (Issue #2) 这个安装包版本其实用的是安装后替换了注册表，可以去注册表里修改一下改成默认值。例如：msyh.ttc 可以参考这个文章 https://blog.csdn.net/Xm3333691/article/details/120482343 ，如果还不行的话，根据名称去卸载一下安装好的字体。 感谢，不过我换的是新版微软雅黑，字体文件名跟旧版完全一样，导致新的直接把旧的覆盖了，但注册表里的值没变……因为系统正在使用这些字体，也卸载不了。这种情况只能重装系统了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

哦哦，正在烦恼重装系统没法完全保留数据呢，谢谢！！您已经帮到我很多了！我先找官方字体试试
